service: flights-app
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.9
  architecture: arm64
  memorySize: 10240 
  timeout: 45
  ecr:
    images:
      extract_load:
        path: ./extract_load
      transform_load:
        path: ./transform_load
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - s3:*
          Resource: "*"
functions:
  extract_load:
    image:
      name: extract_load
  transform_load:
    image:
      name: transform_load
resources:
  Resources:
    MyDatabase:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: 20
        DBInstanceIdentifier: ${db_instance_name}
        Engine: postgres
        EngineVersion: 14.7
        Port: 5432
        MasterUsername: ${db_username}
        MasterUserPassword: ${db_password}
        DBInstanceClass: db.t3.micro
        PubliclyAccessible: true
        