service: flights-app
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.9
  architecture: arm64 # If you do not have an m1 or m2 locally, you can remove this
  memorySize: 10240 
  timeout: 45
  ecr:
    images:
      extract_load:
        path: ./extract_load      
  iam:
functions:
  